replicaCount: 2

image:
  repository: ghcr.io/gravit-network/gravit-epistemic-verifier
  pullPolicy: IfNotPresent
  tag: "1.0.0"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  host: verifier.gravit.network

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70

prometheus:
  enabled: true
