apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gravit-epistemic-verifier.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: gravit-epistemic-verifier
  template:
    metadata:
      labels:
        app: gravit-epistemic-verifier
    spec:
      containers:
      - name: verifier
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
